-- 코드를 입력하세요
SELECT RI1.FOOD_TYPE, RI1.REST_ID, RI1.REST_NAME, RI1.FAVORITES
FROM REST_INFO AS RI1
WHERE RI1.FAVORITES = (SELECT MAX(RI2.FAVORITES)
                     FROM REST_INFO AS RI2
                    WHERE RI1.FOOD_TYPE = RI2.FOOD_TYPE)
ORDER BY RI1.FOOD_TYPE DESC;