SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT MAX(FI_SUB.LENGTH)
    FROM FISH_INFO AS FI_SUB
    WHERE FI_SUB.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID;
