-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE '2022-01-01' <= BS.SALES_DATE AND BS.SALES_DATE < '2022-02-01' 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;