-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND FP.PRICE = (SELECT MAX(FP2.PRICE) 
               FROM FOOD_PRODUCT AS FP2
               WHERE FP.CATEGORY = FP2.CATEGORY)
ORDER BY MAX_PRICE DESC;